### ISSUE TITLE
`hypper uninstall` not working correctly

### ISSUE THREAD

**Issue by kkaempf** [rancher-sandbox/hypper#77]
This is probably related to #73 and #75.

## tl;dr

`hypper uninstall` fails where `helm uninstall` succeeds.

---

I'm following the [chimera-controller install instructions](https://github.com/chimera-kube/chimera-controller#installation), replacing `helm` with `hypper`:

```
$ hypper install --namespace chimera --create-namespace chimera-controller chimera/chimera-controller
```

A subsequent uninstall, although reported as successfull, doesn't actually uninstall the controller.

```
$ hypper uninstall --namespace chimera chimera-controller
🔥  uninstalling chimera-controller
🔥  release "chimera-controller" uninstalled
```

`k9s` still shows `chimera-controller` as running.

Repeating the `hypper uninstall` results in:
```
hypper uninstall --namespace chimera chimera-controller
🔥  uninstalling chimera-controller
Error: uninstall: Release not loaded: chimera-controller: release: not found
```

Doing the same install/uninstall sequence with `helm` works as expected.

**Comment by dragonchaser** [comment]
Is it possible that this is the same issue like #74 ?

**Comment by viccuad** [comment]
Just tried on current main, and the issue is still there :crying_cat_face: .

**Comment by Itxaka** [comment]
probably the same issue as  https://github.com/rancher-sandbox/hypper/issues/75 but we broke the `--namespace` flag?

**Comment by Itxaka** [comment]
should be fixed on main! Keep the bugs coming @kkaempf !

**Comment by kkaempf** [comment]
Reopening - still not fixed.

Note: I renamed `helm` to `helm3` and `hypper` to `helm`.

### How to reproduce

- install [Carrier](https://github.com/SUSE/carrier) on [minikube](https://github.com/SUSE/carrier/blob/main/docs/install.md#minikube)
- run `carrier install`
- run `carrier uninstall`

The above fails (with hypper) at
> helm uninstall service-catalog --namespace service-catalog

with a timeout.

Running with the real helm succeeds.

**Comment by kkaempf** [comment]
It's _only_ the 'service-catalog' step that fail, all other `carrier uninstall` commands (calling hypper as helm) succeed.

**Comment by kkaempf** [comment]
Carrier's code for service-catalog management: https://github.com/SUSE/carrier/blob/main/deployments/service_catalog.go

**Comment by Itxaka** [comment]
Writing it down so I dont forget.

Install by carrier is done as follows https://github.com/SUSE/carrier/blob/main/deployments/service_catalog.go#L110:

`"helm %s %s --create-namespace --namespace %s %s", action, ServiceCatalogDeploymentID, ServiceCatalogDeploymentID, tarPath`


Unistall by carrier is done as follows https://github.com/SUSE/carrier/blob/main/deployments/service_catalog.go#L66: 

`"helm uninstall '%s' --namespace %s", ServiceCatalogDeploymentID, ServiceCatalogDeploymentID`

**Comment by Itxaka** [comment]
service catalog comes from https://kubernetes-sigs.github.io/service-catalog/ I think version 0.3.1

**Comment by Itxaka** [comment]
manually doing the same steps as the ones in carrier results in a correct uninstall....

```
# itxaka @ zeus in ~/projects/hypper on git:fix_uninstall_part_deux x [11:54:19] 
$ bin/hypper install service-catalog --create-namespace --namespace service-catalog catalog-0.3.1.tgz 
Installing chart "service-catalog" in namespace "service-catalog"…
W0330 11:54:31.616693  699479 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0330 11:54:31.617335  699479 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0330 11:54:31.617949  699479 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0330 11:54:31.618534  699479 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0330 11:54:31.619152  699479 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0330 11:54:31.619786  699479 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0330 11:54:31.620433  699479 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0330 11:54:31.621046  699479 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0330 11:54:31.621776  699479 warnings.go:70] rbac.authorization.k8s.io/v1beta1 ClusterRole is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRole
W0330 11:54:31.624173  699479 warnings.go:70] rbac.authorization.k8s.io/v1beta1 ClusterRoleBinding is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRoleBinding
W0330 11:54:31.631872  699479 warnings.go:70] admissionregistration.k8s.io/v1beta1 MutatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 MutatingWebhookConfiguration
W0330 11:54:31.632561  699479 warnings.go:70] admissionregistration.k8s.io/v1beta1 ValidatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 ValidatingWebhookConfiguration
W0330 11:54:31.660936  699479 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0330 11:54:31.663892  699479 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0330 11:54:31.663909  699479 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0330 11:54:31.664030  699479 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0330 11:54:31.664091  699479 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0330 11:54:31.664155  699479 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0330 11:54:31.665068  699479 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0330 11:54:31.665248  699479 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0330 11:54:31.669316  699479 warnings.go:70] rbac.authorization.k8s.io/v1beta1 ClusterRole is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRole
W0330 11:54:31.676832  699479 warnings.go:70] rbac.authorization.k8s.io/v1beta1 ClusterRoleBinding is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRoleBinding
W0330 11:54:31.731014  699479 warnings.go:70] admissionregistration.k8s.io/v1beta1 MutatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 MutatingWebhookConfiguration
W0330 11:54:31.748408  699479 warnings.go:70] admissionregistration.k8s.io/v1beta1 ValidatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 ValidatingWebhookConfiguration
Done! 👏 

# itxaka @ zeus in ~/projects/hypper on git:fix_uninstall_part_deux x [11:54:31] 
$ bin/hypper list                                                                                    
NAME	NAMESPACE	REVISION	UPDATED	STATUS	CHART	APP VERSION

# itxaka @ zeus in ~/projects/hypper on git:fix_uninstall_part_deux x [11:54:42] 
$ bin/hypper list --all-namespaces        
NAME           	NAMESPACE      	REVISION	UPDATED                                 	STATUS  	CHART        	APP VERSION
service-catalog	service-catalog	1       	2021-03-30 11:54:31.288387799 +0200 CEST	deployed	catalog-0.3.1	           

# itxaka @ zeus in ~/projects/hypper on git:fix_uninstall_part_deux x [11:54:46] 
$ bin/hypper uninstall 'service-catalog' --namespace service-catalog
🔥  uninstalling service-catalog
W0330 11:58:04.250846  700499 warnings.go:70] rbac.authorization.k8s.io/v1beta1 ClusterRoleBinding is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRoleBinding
W0330 11:58:04.264638  700499 warnings.go:70] rbac.authorization.k8s.io/v1beta1 ClusterRole is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRole
W0330 11:58:04.267338  700499 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0330 11:58:04.267418  700499 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0330 11:58:04.267461  700499 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0330 11:58:04.267500  700499 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0330 11:58:04.267579  700499 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0330 11:58:04.267626  700499 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0330 11:58:04.267657  700499 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0330 11:58:04.267689  700499 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0330 11:58:04.287854  700499 warnings.go:70] admissionregistration.k8s.io/v1beta1 MutatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 MutatingWebhookConfiguration
W0330 11:58:04.293979  700499 warnings.go:70] admissionregistration.k8s.io/v1beta1 ValidatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 ValidatingWebhookConfiguration
🔥  release "service-catalog" uninstalled
```

**Comment by kkaempf** [comment]
Adding  @andreas-kupries to shed some light on how service-catalog is installed/uninstalled within Carrier.

**Comment by Itxaka** [comment]
with carrier installed:

```
# itxaka @ zeus in ~/projects/hypper on git:fix_uninstall_part_deux x [13:31:56] 
$ bin/hypper list --all-namespaces
NAME            	NAMESPACE       	REVISION	UPDATED                                 	STATUS  	CHART                   	APP VERSION
carrier-registry	carrier-registry	1       	2021-03-30 13:29:03.667376481 +0200 CEST	deployed	container-registry-0.1.0	           
gitea           	gitea           	1       	2021-03-30 13:28:12.81592632 +0200 CEST 	deployed	gitea-2.1.3             	1.13.0     
quarks          	quarks          	1       	2021-03-30 13:28:07.669036985 +0200 CEST	deployed	quarks-secret-1.0.760   	1.0.760    
service-catalog 	service-catalog 	1       	2021-03-30 13:30:11.260470451 +0200 CEST	deployed	catalog-0.3.1           	           
traefik         	traefik         	1       	2021-03-30 13:27:50.724223208 +0200 CEST	deployed	traefik-9.11.0          	2.3.3 
```


calling uninstall works:

```
# itxaka @ zeus in ~/projects/carrier on git:main x [13:30:35] 
$ dist/carrier-linux-amd64 --verbosity 1 --trace-level 2 uninstall
2021/03/30 13:32:52 InstallClient/Uninstall "level"=1 "msg"="start"  

🚢 Carrier uninstalling...
2021/03/30 13:32:52 InstallClient/Uninstall "level"=2 "msg"="remove"  "Deployment"="minibroker"

🚢 Removing Minibroker...

⚠️  Skipping Minibroker because namespace either doesn't exist or not owned by Carrier
2021/03/30 13:32:52 InstallClient/Uninstall "level"=2 "msg"="remove"  "Deployment"="google-service-broker"

🚢 Removing GoogleServices...

⚠️  Skipping GoogleServices because namespace either doesn't exist or not owned by Carrier
2021/03/30 13:32:52 InstallClient/Uninstall "level"=2 "msg"="remove"  "Deployment"="service-catalog"

🚢 Removing ServiceCatalog...

🕞   Removing helm release service-catalog .......

🕞   Deleting ServiceCatalog namespace service-catalog .

✔️  ServiceCatalog removed
2021/03/30 13:32:59 InstallClient/Uninstall "level"=2 "msg"="remove"  "Deployment"="carrier-workloads"

🚢 Removing Workloads...

🕞   Deleting Workloads namespace carrier-workloads .

🕞   Waiting for workloads namespace to be gone .............................................

✔️  Workloads removed
2021/03/30 13:33:44 InstallClient/Uninstall "level"=2 "msg"="remove"  "Deployment"="tekton"

🚢 Removing Tekton...

🕞   Deleting Tekton namespace tekton-pipelines .

✔️  Tekton removed
2021/03/30 13:33:45 InstallClient/Uninstall "level"=2 "msg"="remove"  "Deployment"="carrier-registry"

🚢 Removing Registry...

🕞   Removing helm release carrier-registry .

🕞   Deleting Registry namespace carrier-registry .

✔️  Registry removed
2021/03/30 13:33:46 InstallClient/Uninstall "level"=2 "msg"="remove"  "Deployment"="gitea"

🚢 Removing Gitea...

🕞   Removing helm release gitea .

🕞   Deleting Gitea namespace gitea .

✔️  Gitea removed
2021/03/30 13:33:47 InstallClient/Uninstall "level"=2 "msg"="remove"  "Deployment"="quarks"

🚢 Removing Quarks...

🕞   Removing helm release quarks .

🕞   Deleting Quarks namespace quarks .

✔️  Quarks removed
2021/03/30 13:33:48 InstallClient/Uninstall "level"=2 "msg"="remove"  "Deployment"="traefik"

🚢 Removing Traefik...

🕞   Removing helm release traefik .

🕞   Deleting Traefik namespace traefik .

✔️  Traefik removed

✔️  Carrier uninstalled.
2021/03/30 13:33:49 InstallClient/Uninstall "level"=1 "msg"="return"  

```

And everything is cleaned up:

```
# itxaka @ zeus in ~/projects/hypper on git:fix_uninstall_part_deux x [13:33:50] 
$ bin/hypper list --all-namespaces
NAME	NAMESPACE	REVISION	UPDATED	STATUS	CHART	APP VERSION
```


Version confirmation (substituted helm binary for hypper):
```
# itxaka @ zeus in ~/projects/hypper on git:fix_uninstall_part_deux x [13:37:17] C:1
$ helm version 
version.BuildInfo{Version:"", GitCommit:"9f6c4852b0d7ea3751e975763ec88e5940a0a95a", GoVersion:"go1.16"}
```


Can you retry this @kkaempf as I cant reproduce it.

**Comment by Itxaka** [comment]
also carrier version (master):

```
# itxaka @ zeus in ~/projects/carrier on git:main x [13:50:10] 
$ dist/carrier-linux-amd64 --version                              
carrier version v0.0.5-34-gdf5065e

```

**Comment by Itxaka** [comment]
Blocked due to awaiting @kkaempf retry of this issue to see if there is any conditions required to trigger it.
